services:
  audiarr:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./test-music:/music:ro
      - audiarr_data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MUSIC_LIBRARY_PATH=/music
    container_name: audiarr-server
    restart: unless-stopped

volumes:
  audiarr_data:
