services:
    audiarr-server:
        ports:
            - 5279:5279
        volumes:
            - /mnt/Media/Music:/music
            - /home/docker/audiarr/config:/config
        container_name: audiarr-server
        image: audiarr-server
